name: ExpTech_DataRecord
version: 2.3
author: whes1015
main: main.main
api-version: 1.18

commands:
  dr:
    description: 控制 ExpTech_DataRecord 插件
    usage: /dr <args>
    permission: exptech.admin